version: 0.0
os: linux

files:
  - source: .
    destination: /home/ec2-user/Tortuga-Node
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/setup_node.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
