version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/Tortuga-Node
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/clean_directory.sh
      timeout: 60
    - location: scripts/stop_server.sh
      timeout: 60
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
  ApplicationStart:
    - location: start_server.sh
      timeout: 60
      runas: ec2-user
