name: Deploy Node App to EC2 with CodeDeploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip source code
        run: |
          zip -r deployment-package.zip .

      - name: Upload to S3
        run: |
          aws s3 cp deployment-package.zip s3://tortuga-node-api-deployments/deployment-package.zip

      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.DEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.DEPLOY_GROUP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=tortuga-node-api-deployments,bundleType=zip,key=deployment-package.zip
